apt:
  gpg:
    - https://apt.releases.hashicorp.com/gpg
    - http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367
    - https://download.docker.com/linux/ubuntu/gpg
  repositories: 
    - "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    - "ppa:deadsnakes/ppa"
    - "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_distribution_release | lower }} main"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
  packages: 
    - ansible
    - ansible-lint
    - pass
    - vagrant
    - packer
    - vault
    - terraform 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

python: 
  versions: 
    - "3.8"
    - "3.9"
    - "3.10"


snapd:
  - code
  - kontena-lens

vscode: 
  user: adelisle
  extensions: 
    - tomaciazek.ansible
    - davidanson.vscode-markdownlint
    - donjayamanne.python-extension-pack
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
