
- name: ADD APT GPGs
  apt_key:
    url: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ apt.gpg }}"
- name: ADD APT REPOSITORIES
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt.repositories }}"
- name: UPDATE AND UPGRADE APT PACKAGES
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: INSTALL APT PACKAGES
  become: yes
  apt:
    pkg: "{{ apt.packages }}"
    state: latest
    update_cache: yes

- name: Install SNAPD packages
  become: yes
  community.general.snap:
    name: "{{ snapd }}"
    classic: yes

- name: Install Python Version
  become: yes
  with_items: "{{ python.versions }}"
  apt:
    pkg: "python{{ item }}"
    state: latest
    update_cache: yes

- name: Install Python Utils
  become: yes
  with_items: "{{ python.versions }}"
  apt:
    pkg: "python{{ item }}-distutils"
    state: latest
    update_cache: yes


- name: Creates directory for VS Code Extensions
  file:
    path: /home/{{ vscode.user }}/.vscode/extensions
    state: directory

- name: Creates directory for VS Code Extensions
  command: code --extensions-dir /home/{{ vscode.user }}/.vscode/extensions
  

- name: Creates directory for VS Code Extensions
  with_items: "{{ vscode.extensions }}"
  register: vscodextout
  command: code --install-extension {{ item }}
  changed_when: "'already installed.' not in vscodextout.stdout"
