# Default theme
oh_my_zsh_theme: robbyrussell

# Default plugins
oh_my_zsh_plugins:
  - zsh-autosuggestions
  - history
  - jsontools
  - ubuntu
  - kubectl
  - git
  - safe-paste  
  - sudo
users:
  - username: adelisle
    visual_studio_code_extensions:
     - tomaciazek.ansible
     - davidanson.vscode-markdownlint
     - donjayamanne.python-extension-pack
     - hashicorp.terraform
     - ms-azuretools.vscode-docker
